/**
 * Permit data sources — City of San Diego is automated (CSV / OData).
 * Other cities: confirmed public search URLs + stack; Accela Construct when OAuth + agency are provisioned.
 */

/** Accela Construct `x-accela-agency` values the app must be registered for (Tyler Accela developer portal). */
export const ACCELA_AGENCIES_PRIORITY = [
  {
    sourceCityLabel: 'Chula Vista',
    agencyCode: 'CHULAVISTA',
    citizenPortalUrl: 'https://permits.chulavistaca.gov/citizenaccess/',
  },
  {
    sourceCityLabel: 'National City',
    agencyCode: 'PRCITY',
    citizenPortalUrl: 'https://aca-prod.accela.com/PRCITY/Default.aspx',
  },
];

export const PERMIT_JURISDICTIONS = [
  {
    id: 'san_diego',
    sourceCityLabel: 'San Diego',
    priority: 'baseline',
    portalUrl: 'https://data.sandiego.gov/',
    publicPermitSearchUrl: 'https://data.sandiego.gov/dataset/development-permits-set2',
    stack: 'Socrata / City open data (OData + active CSV)',
    automationMode: 'automated_csv',
    dataMethod: 'automated_csv',
    filters: 'ADU, new construction, remodel, addition (mapped from approval types; water-heater / standalone plumbing permits excluded — already covered by other plumbers)',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: false,
  },
  {
    id: 'chula_vista',
    sourceCityLabel: 'Chula Vista',
    priority: '1',
    portalUrl: 'https://www.chulavistaca.gov/departments/development-services/building',
    publicPermitSearchUrl: 'https://permits.chulavistaca.gov/citizenaccess/',
    stack: 'Accela Citizen Access (hosted) + Accela Construct API',
    automationMode: 'accela_construct_when_configured',
    dataMethod: 'accela_portal',
    filters: 'ADU, remodel, new construction',
    accelaCitizenAccess: 'https://permits.chulavistaca.gov/citizenaccess/',
    accelaAgencyCode: 'CHULAVISTA',
    manualCheckRequired: false,
    notes:
      'Citizen Access confirmed. Server pull uses Accela Construct API when ACCELA_CLIENT_ID/SECRET are set and the app is provisioned for agency CHULAVISTA; otherwise no automated rows.',
  },
  {
    id: 'national_city',
    sourceCityLabel: 'National City',
    priority: '2',
    portalUrl: 'https://www.nationalcityca.gov/government/community-development/building',
    publicPermitSearchUrl: 'https://aca-prod.accela.com/PRCITY/Default.aspx',
    stack: 'Accela Citizen Access on aca-prod (agency PRCITY) + Accela Construct API',
    automationMode: 'accela_construct_when_configured',
    dataMethod: 'accela_portal',
    filters: 'Residential permits, commercial TI',
    accelaCitizenAccess: 'https://aca-prod.accela.com/PRCITY/Default.aspx',
    accelaAgencyCode: 'PRCITY',
    manualCheckRequired: false,
    notes: 'Public Accela Citizen Access host uses path /PRCITY/ — confirm with National City if they change hosts.',
  },
  {
    id: 'el_cajon',
    sourceCityLabel: 'El Cajon',
    priority: '3',
    portalUrl: 'https://www.elcajon.gov/doing-business/building-and-fire-permits',
    publicPermitSearchUrl: 'https://elcajonca-energovpub.tylerhost.net/Apps/SelfService#/home',
    stack: 'Tyler Energov Self-Service (PACO / online permitting)',
    automationMode: 'scrape_or_api_tbd',
    dataMethod: 'tyler_energov',
    filters: 'ADU, remodel, new construction',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
    notes: 'City materials reference Tyler-hosted Self-Service (not Accela). Scraper/API integration pending.',
  },
  {
    id: 'la_mesa',
    sourceCityLabel: 'La Mesa',
    priority: '4',
    portalUrl: 'https://www.cityoflamesa.gov/111/Building',
    publicPermitSearchUrl: 'https://h9.maintstar.co/LaMesa/portal/#/',
    stack: 'MaintStar permit portal',
    automationMode: 'scrape_or_api_tbd',
    dataMethod: 'maintstar',
    filters: 'Residential and commercial permits',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
    notes: 'MaintStar hosted portal — likely SPA; needs dedicated integration or headless search.',
  },
  {
    id: 'poway',
    sourceCityLabel: 'Poway',
    priority: '5',
    portalUrl: 'https://www.poway.org/197/Building',
    publicPermitSearchUrl: 'https://selfservice.poway.org/energov_prod/selfservice#/home',
    stack: 'Tyler Energov Self-Service',
    automationMode: 'scrape_or_api_tbd',
    dataMethod: 'tyler_energov',
    filters: 'New construction, ADU, remodel',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
    notes: 'Alternate entry: services.poway.org/EnerGov_Prod/SelfService — confirm with city.',
  },
  {
    id: 'coronado',
    sourceCityLabel: 'Coronado',
    priority: '6',
    portalUrl: 'https://www.coronado.ca.us/238/Community-Development',
    publicPermitSearchUrl: 'https://ca-coronado.civicplus.com/300/Permits',
    stack: 'CivicPlus municipal site (permit content)',
    automationMode: 'scrape_or_api_tbd',
    dataMethod: 'civicplus',
    filters: 'ADU, remodel, new construction',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
    notes: 'No public machine API identified; CivicPlus pages vary — scrape or vendor API TBD.',
  },
  {
    id: 'del_mar',
    sourceCityLabel: 'Del Mar',
    priority: '7',
    portalUrl: 'https://www.delmar.ca.us/202/Building-Department',
    publicPermitSearchUrl: 'https://delm-trk.aspgov.com/eTRAKiT/Search/permit.aspx',
    stack: 'eTRAKiT (ASP.NET)',
    automationMode: 'scrape_or_api_tbd',
    dataMethod: 'etrakit',
    filters: 'ADU, remodel, new construction',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
    notes: 'Classic eTRAKiT search — typically ViewState POST flow for scraping.',
  },
  {
    id: 'solana_beach',
    sourceCityLabel: 'Solana Beach',
    priority: '8',
    portalUrl: 'https://www.cosb.us/departments/community-development/building',
    publicPermitSearchUrl: 'https://solab-trk.aspgov.com/eTRAKiT/Search/permit.aspx',
    stack: 'eTRAKiT (ASP.NET)',
    automationMode: 'scrape_or_api_tbd',
    dataMethod: 'etrakit',
    filters: 'ADU, remodel, new construction',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
    notes: 'Same product family as Del Mar (eTRAKiT) — separate agency instance.',
  },
  {
    id: 'santee',
    sourceCityLabel: 'Santee',
    priority: 'medium',
    portalUrl: 'https://www.cityofsanteeca.gov/departments/public-works/building-division',
    publicPermitSearchUrl: null,
    stack: 'TBD — confirm with city',
    automationMode: 'portal_unknown',
    dataMethod: 'portal_search',
    filters: 'Building permits',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
  },
  {
    id: 'escondido',
    sourceCityLabel: 'Escondido',
    priority: 'medium',
    portalUrl: 'https://www.escondido.org/building.aspx',
    publicPermitSearchUrl: null,
    stack: 'Cityworks-style (not Accela)',
    automationMode: 'portal_unknown',
    dataMethod: 'cityworks_portal',
    filters: 'Construction permits',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
    notes: 'Materials often reference Cityworks online portal — different stack than Accela.',
  },
  {
    id: 'san_marcos',
    sourceCityLabel: 'San Marcos',
    priority: 'medium',
    portalUrl: 'https://www.san-marcos.net/departments/development-services',
    publicPermitSearchUrl: null,
    stack: 'TBD — confirm with city',
    automationMode: 'portal_unknown',
    dataMethod: 'portal_search',
    filters: 'Building permits',
    accelaCitizenAccess: null,
    accelaAgencyCode: null,
    manualCheckRequired: true,
  },
];

export const CITIES_MONITORED_COUNT = PERMIT_JURISDICTIONS.length;

export const ACCELA_STANDARDIZATION_NOTE = [
  'Chula Vista: Accela Citizen Access at permits.chulavistaca.gov; Construct API agency code CHULAVISTA.',
  'National City: Accela on aca-prod.accela.com/PRCITY; Construct agency code PRCITY.',
  'El Cajon / Poway: Tyler Energov self-service (not Accela).',
  'La Mesa: MaintStar.',
  'Del Mar / Solana Beach: eTRAKiT (ASP.NET).',
  'Coronado: CivicPlus site pages — integration TBD.',
  'OAuth for Construct is per developer app at developer.accela.com; agencies must be entitled on that app.',
].join(' ');
