/**
 * Pre-loaded San Diego vendor directory for Tri Express Plumbing.
 * Exactly 26 companies per product spec (full brief lists more; this is the curated set).
 */
export const SEED_VENDORS = [
  // Restoration (8)
  {
    name: 'Christian Brothers Emergency Building Services',
    contact_person: '',
    email: '',
    phone: '619-469-8955',
    category: 'restoration',
    notes: 'Lakeside.',
  },
  {
    name: 'Integrity Restoration, Inc.',
    contact_person: '',
    email: '',
    phone: '858-270-9151',
    category: 'restoration',
    notes: 'San Diego. 12-year partnership with Tri Express — primary proof point.',
  },
  {
    name: 'Orange Restoration',
    contact_person: '',
    email: '',
    phone: '',
    category: 'restoration',
    notes: 'San Diego. Master plumber on staff.',
  },
  {
    name: 'Water Mold Fire Restoration',
    contact_person: '',
    email: '',
    phone: '619-900-4211',
    category: 'restoration',
    notes: '10+ years.',
  },
  {
    name: 'SERVPRO (San Diego — multiple franchises)',
    contact_person: '',
    email: '',
    phone: '',
    category: 'restoration',
    notes: '4 locations in San Diego County.',
  },
  {
    name: 'Paul Davis Restoration (North & South County)',
    contact_person: '',
    email: '',
    phone: '',
    category: 'restoration',
    notes: '2 locations.',
  },
  {
    name: 'Restoration Solutions',
    contact_person: 'Jim Thurber',
    email: '',
    phone: '',
    category: 'restoration',
    notes: 'San Diego. Contact: Jim Thurber.',
  },
  {
    name: 'PuroClean Emergency Services',
    contact_person: '',
    email: '',
    phone: '858-566-7876',
    category: 'restoration',
    notes: 'San Diego.',
  },
  // Property management (8)
  {
    name: 'PURE Property Management',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '',
  },
  {
    name: 'Ziprent',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '600 B St.',
  },
  {
    name: 'Realty Management Group (RMG)',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '',
  },
  {
    name: 'Elevate SD Properties',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '',
  },
  {
    name: 'Good Life Property Management',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '',
  },
  {
    name: 'Keyrenter San Diego',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '',
  },
  {
    name: 'Green Street Property Management',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '',
  },
  {
    name: 'Bridgehaus Property Managers',
    contact_person: '',
    email: '',
    phone: '',
    category: 'property_mgmt',
    notes: '',
  },
  // HOA management (5)
  {
    name: 'ASPM San Diego',
    contact_person: '',
    email: '',
    phone: '',
    category: 'hoa',
    notes: 'Since 1971.',
    years_in_business: 'Since 1971',
  },
  {
    name: 'Walters Management',
    contact_person: '',
    email: '',
    phone: '',
    category: 'hoa',
    notes: 'Carlsbad office.',
  },
  {
    name: 'Property Management Consultants (PMC)',
    contact_person: '',
    email: '',
    phone: '',
    category: 'hoa',
    notes: '45+ years.',
  },
  {
    name: 'APS (Associated Professional Services)',
    contact_person: '',
    email: '',
    phone: '',
    category: 'hoa',
    notes: '40+ years.',
  },
  {
    name: 'The Prescott Companies',
    contact_person: '',
    email: '',
    phone: '',
    category: 'hoa',
    notes: '',
  },
  // ADU / remodel contractors (5)
  {
    name: 'Remodel Works',
    contact_person: '',
    email: '',
    phone: '',
    category: 'contractor',
    notes: 'Poway showroom. 40+ years.',
    years_in_business: '40+',
    address: 'Poway',
  },
  {
    name: 'Specialty Design Build',
    contact_person: '',
    email: '',
    phone: '858-759-7400',
    category: 'contractor',
    notes: '',
  },
  {
    name: 'Gary Faith Construction',
    contact_person: '',
    email: '',
    phone: '',
    category: 'contractor',
    notes: '',
  },
  {
    name: 'North County ADU Construction Contractors',
    contact_person: '',
    email: '',
    phone: '',
    category: 'contractor',
    notes: '',
  },
  {
    name: 'Nestadu',
    contact_person: '',
    email: '',
    phone: '',
    category: 'contractor',
    notes: 'ADU specialist.',
  },
];
